[package]
name = "wanted-templates"
version = "0.1.0"
authors = ["Erutuon <5840197+Erutuon@users.noreply.github.com>"]
edition = "2018"

[dependencies]
parse-mediawiki-sql = { version = "0.9.0", features = ["utils"] }
pico-args = "0.5.0"
anyhow = "1.0.33"
unicase = "2.6"
