[package]
name = "wanted-templates"
version = "0.1.0"
authors = ["Erutuon <5840197+Erutuon@users.noreply.github.com>"]
edition = "2018"

[dependencies]
parse-mediawiki-sql = "0.4.0"
memmap = "0.7.0"
pico-args = "0.3"
anyhow = "1.0.33"
thiserror = "1.0.21"
unicase = "2.6.0"
